<?php

use Illuminate\Database\Seeder;

class StudentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $students = [
			[ 'register_no'=>'2017/CSC/001', 
                'index_no'=>'S9901 ',
                'name'=>'Janani Kangesan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/002',
                'index_no'=>'S9902 ',
                'name'=>'Dissanayaka Mudiyanselage Shalika Harshani Dissanayaka',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/003', 
                'index_no'=>'S9903 ',
                'name'=>'Krishnamoorthy Thanushan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/004', 
                'index_no'=>'S9904 ',
                'name'=>'Supasthika Amirthalingam', 
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/005', 
                'index_no'=>'S9905 ',
                'name'=>'Srikaran Jatheesan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/006', 
                'index_no'=>'S9906 ',
                'name'=>'Divya Varatharajan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/007', 
                'index_no'=>'S9907 ',
                'name'=>'Samarasinghage Kavindya Sathsarani',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/008', 
                'index_no'=>'S9908 ',
                'name'=>'Sinthuja Arumainayagam',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/009', 
                'index_no'=>'S9909 ',
                'name'=>'Rathnayakage Amila Saranga Rathnayaka',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/010', 
                'index_no'=>'S9910 ',
                'name'=>'Abdul Gaffar Mohamed Fawzy',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/011', 
                'index_no'=>'S9911 ',
                'name'=>'Yaleen Mohamed Silhan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/012', 
                'index_no'=>'S9912 ',
                'name'=>'Niranga Sithara Athauda Arachchi',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
             [
                'register_no'=>'2017/CSC/013', 
                'index_no'=>'S9913 ',
                'name'=>'hanganna Gamage Tharindu Prasad Ranaweera',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/014', 
                'index_no'=>'S9914 ',
                'name'=>'Samarakoon Jayasekara Mudiyanselage Imila Maheshan Bandara Samarakoon',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/015', 
                'index_no'=>'S9915 ',
                'name'=>'Musthafa Lebbe Mohamed Sanoos',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/016', 
                'index_no'=>'S9916',
                'name'=>'Aluthgamaralalage Isuru Lakmal',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/017', 
                'index_no'=>'S9917 ',
                'name'=>'Mohommadhu Abdhul Rahoof Rifath Muhammadh',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/018', 
                'index_no'=>'S9918 ',
                'name'=>'Elackshana Manivannan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/019', 
                'index_no'=>'S9919 ',
                'name'=>'Mohammed Hilmy Mohammed Himaz',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/020', 
                'index_no'=>'S9920 ',
                'name'=>'Mohamed Ismail Ahamed Aneeque',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/021', 
                'index_no'=>'S9922 ',
                'name'=>'Mohommadhu Hanifa Mohommadhu Hisham',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/022', 
                'index_no'=>'S9923 ',
                'name'=>'Dilki Hasara Wickramasinghe',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/023', 
                'index_no'=>'S9925',
                'name'=>'Mathiyalagan Mathusha',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/024', 
                'index_no'=>'S9927',
                'name'=>'Mapa Mudiyanselage Madhawa Heshan Thilakarathne',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/026', 
                'index_no'=>'S9928 ',
                'name'=>'Wijesundara lekamlage Chamika Sandaruwan Wijesundara',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/027', 
                'index_no'=>'S9929 ',
                'name'=>'Panadura Acharige Wijesundara Gunathilaka Ramesh Perera',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/028', 
                'index_no'=>'S9930 ',
                'name'=>'Dissanayaka Mudiyanselage Sudula Kumara Dissanayaka',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/029', 
                'index_no'=>'S9931 ',
                'name'=>'Uthumalebbe Mohamed Afrid',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/030', 
                'index_no'=>'S9932 ',
                'name'=>'Kishani Kandasamy',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/031', 
                'index_no'=>'S9934 ',
                'name'=>'Lansakara Herath Mudiyanselage Bisak Sampath Bandara',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/032', 
                'index_no'=>'S9936 ',
                'name'=>'Prathaban Kavin', 
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/033', 
                'index_no'=>'S9860 ',
                'name'=>'Pushpakantha Ajanthasiri Gamage',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/034', 
                'index_no'=>'S9864 ',
                'name'=>'Vetharsana Thangarajah',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/035', 
                'index_no'=>'S9865 ',
                'name'=>'Hewa Puwakdandawage Isuru Madushan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/036', 
                'index_no'=>'S9867 ',
                'name'=>'Ekanayake Mudiyanselage Charith Gihan Ekanayake',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/037', 
                'index_no'=>'S9868 ',
                'name'=>'Panojah Nadarasa',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/038', 
                'index_no'=>'S9869 ',
                'name'=>'Meiyalagan Yathushanan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'20880459 ',
                'index_no'=>'S9870 ',
                'name'=>'Kirusnashamy Kisnakumar',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/040', 
                'index_no'=>'S9881 ',
                'name'=>'Karthikesu Kogul',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/041', 
                'index_no'=>'S9882 ',
                'name'=>'Sritharan Kajith',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/042', 
                'index_no'=>'S9883 ',
                'name'=>'Linganathan Kiritharan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/043', 
                'index_no'=>'S9884 ',
                'name'=>'Selvakumar Ranjithamalar',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/044', 
                'index_no'=>'S9885 ',
                'name'=>'mallawa Arachchige Heshan Nayanajith mallawarachchi',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/045', 
                'index_no'=>'S9886 ',
                'name'=>'Zahir Mohamed Ardil',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/046', 
                'index_no'=>'S9887 ',
                'name'=>'Sethukavalan Lokavanilavan',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/047', 
                'index_no'=>'S9888 ',
                'name'=>'Rathnayaka Mudiyanselage Lukshan kavinda',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/048', 
                'index_no'=>'S9889 ',
                'name'=>'Herath Mudiyanselage Cathuranga Sanjeewa rathnayake',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/CSC/049', 
                'index_no'=>'S9890 ',
                'name'=>'Nawab Yousufi',
                'level' =>'1S',
                'yos' =>'2017/2018',
               ],
               
           //1G	
           [
                'register_no'=>'2016/SP/040', 
                'index_no'=>'S9937 ',
                'name'=>'Herath Mudiyanselage Jithmi Nayanathara Herath',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/002', 
                'index_no'=>'S9938 ',
                'name'=>'Vishnuga Sivakumaran',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/003', 
                'index_no'=>'S9940 ',
                'name'=>'Thirisika Pragalathanan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/005', 
                'index_no'=>'S9942 ',
                'name'=>'Sithamparanadesan Kumareasan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/006', 
                'index_no'=>'S9943 ',
                'name'=>'Nishani Poovalingam',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/008', 
                'index_no'=>'S9944 ',
                'name'=>'Nagaraja Senthuran',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/009', 
                'index_no'=>'S9945 ',
                'name'=>'Kugapriya Kumarasamy',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/010', 
                'index_no'=>'S9947 ',
                'name'=>'Sathiyaseelan Kosika',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/011', 
                'index_no'=>'S9950 ',
                'name'=>'Luxsana Paramaseelan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/012', 
                'index_no'=>'S9952 ',
                'name'=>'Mageswaran Janarthanan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/013', 
                'index_no'=>'S9956 ',
                'name'=>'Thuvaraka Thiraviyarasa',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/014', 
                'index_no'=>'S9957 ',
                'name'=>'Mithusa Thillaivasan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/015', 
                'index_no'=>'S9959 ',
                'name'=>'Louis Mariyanayakam Premitha',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/016', 
                'index_no'=>'S9960 ',
                'name'=>'Gnanasegaram Sulojana',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/017', 
                'index_no'=>'S9962 ',
                'name'=>'Nanthakumar Pakirathan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/018', 
                'index_no'=>'S9963 ',
                'name'=>'Ganesharajan Anojan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/020', 
                'index_no'=>'S9964 ',
                'name'=>'Thayani jeganathan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/024', 
                'index_no'=>'S9967 ',
                'name'=>'Rajakaruna Herath Mudiyanselage Mayuri Shanika Rajakaruna',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/025', 
                'index_no'=>'S9968 ',
                'name'=>'Maharaja Thinesh',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/029', 
                'index_no'=>'S9969 ',
                'name'=>'Dilaxsha Thangarasa',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/031', 
                'index_no'=>'S9970 ',
                'name'=>'Subramaniam Prashanth',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/032', 
                'index_no'=>'S9971 ',
                'name'=>'Rajanageswaran Justilla',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/034', 
                'index_no'=>'S9071 ',
                'name'=>'Perinpanathan Mathusha',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/035', 
                'index_no'=>'S9972 ',
                'name'=>'Walamuni Dewage Shanilka Wijesingha',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/040', 
                'index_no'=>'S9973 ',
                'name'=>'Dassanayaka Mudiyanselage rasika Lakmal Dassanayaka',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/042', 
                'index_no'=>'S9974 ',
                'name'=>'Rathnayaka Mudiyanselage Isuru Udara rathnayake',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/044', 
                'index_no'=>'S9975 ',
                'name'=>'Samarakoon Ralalage Maneesha Devni Samarakoon',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/045', 
                'index_no'=>'S9976 ',
                'name'=>'Sabaraththinam Vithusla',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/046', 
                'index_no'=>'S9977 ',
                'name'=>'Konthadoru Thambiralalage lakshika Ishani kumari Silva',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
             [
                'register_no'=>'2017/SP/047', 
                'index_no'=>'S9978 ',
                'name'=>'Keerthiga Thiruganasothy',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/048', 
                'index_no'=>'S9979 ',
                'name'=>'yahathugoda Badalge Kalana Pasindu De Kostha',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/049', 
                'index_no'=>'S9980 ',
                'name'=>'Kashthury Gunabalasingam',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/050', 
                'index_no'=>'S9981 ',
                'name'=>'Liyana ralalage Lalitha Widhuranga Weerawardhana',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/056', 
                'index_no'=>'S9982 ',
                'name'=>'Varaginy Subramaniyam',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/057', 
                'index_no'=>'S9983 ',
                'name'=>'Thavachchelvam Nitharsini',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
               [
                'register_no'=>'2017/SP/058', 
                'index_no'=>'S9984 ',
                'name'=>'Weebadde weerakoon Mudiyanselage Hapugaskumbure Avishka Saum',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/059', 
                'index_no'=>'S9985 ',
                'name'=>'Pathirage Don Samitha Dilan Pathirade',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/060', 
                'index_no'=>'S9986 ',
                'name'=>'Sammu Vishwa Sasanka',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/063', 
                'index_no'=>'S9987 ',
                'name'=>'Vigneswaran Khariharan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/066', 
                'index_no'=>'S9988 ',
                'name'=>'Karunagaran Kaarunja', 
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/067', 
                'index_no'=>'S9989 ',
                'name'=>'Kirindawa Liyanage Sandun Prabath Senarathna',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/068', 
                'index_no'=>'S9991 ',
                'name'=>'Yayakody Arachchilage Lakmi Nayananjali Jayakody',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/084', 
                'index_no'=>'S9992 ',
                'name'=>'Wickrama Arachchige Rumali Tharushika Gunasekara',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/091', 
                'index_no'=>'S9993 ',
                'name'=>'Rajapakshage Nuwan Nalaka Rajapaksha',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/143', 
                'index_no'=>'S9994 ',
                'name'=>'Chandran Nivethan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/166', 
                'index_no'=>'S9995 ',
                'name'=>'Ranasinghe Rukshan Akshitha Prasanga',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/167', 
                'index_no'=>'S9996 ',
                'name'=>'Kavikshana Ujenda Premalal', 
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/187', 
                'index_no'=>'S9997 ',
                'name'=>'Francis Robert Dunstan Leon',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/188', 
                'index_no'=>'S9998 ',
                'name'=>'Sabaratinam Subaskar',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/233', 
                'index_no'=>'S9999 ',
                'name'=>'Morawakalage Sandun Chathuranga',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/279', 
                'index_no'=>'S9825 ',
                'name'=>'Sreesangameera Sreeskantharajaah', 
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/280', 
                'index_no'=>'S9826 ',
                'name'=>'Mathanki Amirthalingam', 
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
           [
                'register_no'=>'2017/SP/287', 
                'index_no'=>'S9827 ',
                'name'=>'Raththinasingkam Vipooshanan',
                'level' =>'1G',
                'yos' =>'2017/2018',
               ],
   
           //2S
           [
                'register_no'=>'2015/CSC/001', 
                'index_no'=>'S9459 ',
                'name'=>'S. Lesslylavan',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/001', 
                'index_no'=>'S9059 ',
                'name'=>'Samsudeen Munawwar Ahamed',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/002', 
                'index_no'=>'S9320 ',
                'name'=>'Mohamed Ahamed Arham',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/003', 
                'index_no'=>'S9323 ',
                'name'=>'A.A.S.N.Athauda', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/004', 
                'index_no'=>'S9325 ',
                'name'=>'S.A.Samila Chanuka',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/005', 
                'index_no'=>'S9340',
                'name'=>'R.H.S.L.Dilshan',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/007', 
                'index_no'=>'S9342 ',
                'name'=>'W.Nimasha Nishadi Fernando',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/008', 
                'index_no'=>'S9346 ',
                'name'=>'H.M.D.Herath', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/009', 
                'index_no'=>'S9348 ',
                'name'=> 'S.Jenushanth',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/010', 
                'index_no'=>'S9350 ',
                'name'=>'G.H.G.R.Kalpage',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/011', 
                'index_no'=>'S9352',
                'name'=> 'H.L.R.L.Liyanage',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/012', 
                'index_no'=>'S9356 ',
                'name'=>'M.Mathanraj',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'20360459 ',
                'index_no'=>'S9357 ',
                'name'=>'A.H.Rasika Priyadarshani',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/019', 
                'index_no'=>'S9362 ',
                'name'=> 'Ramees Mohamed Rizwan',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/020', 
                'index_no'=>'S9367 ',
                'name'=>'U.S.Dilan Samaraweera', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/021', 
                'index_no'=>'S9369 ',
                'name'=>'S.S.K.Anuka Sanjaya',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/023', 
                'index_no'=>'S9370 ',
                'name'=>'Sinthuja Vijayananthan', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/024', 
                'index_no'=>'S9379 ',
                'name'=>'K.Sripalasenthuran',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/025', 
                'index_no'=>'S9380 ',
                'name'=>'T.M.G.C.B.Tennakoon',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/027', 
                'index_no'=>'S9382 ',
                'name'=>'W.R.I.R.Widyasekara', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/028', 
                'index_no'=>'S9383 ',
                'name'=>'Methusha Thuraisingam',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/029', 
                'index_no'=>'S9385 ',
                'name'=>'R.M.C.K.Rathnayake', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/030', 
                'index_no'=>'S9386 ',
                'name'=>'Vithursha Sivakumaran', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/031', 
                'index_no'=>'S9387 ',
                'name'=>'Ajanthy Jayarajan',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/032', 
                'index_no'=>'S9390 ',
                'name'=>'Thushankgi Balachandran', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/033', 
                'index_no'=>'S9400 ',
                'name'=> 'D.M.S.Lakshitha', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/034', 
                'index_no'=>'S9405 ',
                'name'=>'R.M.Yashodha Nilmini', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/035', 
                'index_no'=>'S9406 ',
                'name'=>'Nisamdeen Mohamed Shareek', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/036', 
                'index_no'=>'S9407 ',
                'name'=>'N.A.Muhandiram', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/037', 
                'index_no'=>'S9408 ',
                'name'=>'Siddique Mohamed Wazeem',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/039', 
                'index_no'=>'S9409 ',
                'name'=>'T.D.Pramuditha Chamikara',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/040', 
                'index_no'=>'S9410 ',
                'name'=> 'H.M.Abhimani Sachithra',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/041', 
                'index_no'=>'S9411 ',
                'name'=>'H.W.R.L.Hendrawitharana',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/042', 
                'index_no'=>'S9412 ',
                'name'=>'J.S.Shanfravin',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/043', 
                'index_no'=>'S9413 ',
                'name'=>'Yothika Yogeswaran', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/044', 
                'index_no'=>'S9414 ',
                'name'=>'A.G.Dilshan Dilip Udara',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/045', 
                'index_no'=>'S9415 ',
                'name'=>'A.Keerthikan', 
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/046', 
                'index_no'=>'S9416',
                'name'=>'Abdul Jabbar Mohamed Rizvi',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/047', 
                'index_no'=>'S9417 ',
                'name'=>'N.D.Dodanwala',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/CSC/048', 
                'index_no'=>'S9418 ',
                'name'=>'R.Shehan Lahiru Jayasinghe',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
    [
                'register_no'=>'2016/CSC/038', 
                'index_no'=>'S9419 ',
                'name'=>'S.F.Safna',
                'level' =>'2S',
                'yos' =>'2016/2017',
               ],
   
           //2G
           [
                'register_no'=>'2015/SP/058', 
                'index_no'=>'S9420 ',
                'name'=>'Anton Jesuthas Nickson Joram',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/002', 
                'index_no'=>'S9452 ',
                'name'=>'Ketheeswaran Abiram',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/009', 
                'index_no'=>'S9455 ',
                'name'=>'Manoj Lakshitha Bandara',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/010', 
                'index_no'=>'S9456 ',
                'name'=>'Sahanaa Baskaran',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],		
               [
                'register_no'=>'2016/SP/012', 
                'index_no'=>'S1959 ',
                'name'=>'Ekanayaka Mudiyanselage Shyamali Hasanthika Ekanayaka',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/038', 
                'index_no'=>'S9460 ',
                'name'=>'Somarathnage Surath Miyuru Hasaranjana',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/050', 
                'index_no'=>'S9462 ',
                'name'=>'Veerasingam Kajitha',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
            [
                'register_no'=>'2016/SP/051', 
                'index_no'=>'S9463 ',
                'name'=>'Kesavi Kanesalingam',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/054', 
                'index_no'=>'S9464 ',
                'name'=>'Wijemuni Lahiru Dilshan Karunathilake',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/072', 
                'index_no'=>'S9465 ',
                'name'=>'Sivananthan Marujan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],		
               [
                'register_no'=>'2016/SP/077', 
                'index_no'=>'S9466 ',
                'name'=>'Muhannadhu Nawas Muhammadhu Nafees',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/085', 
                'index_no'=>'S9467 ',
                'name'=>'Manokaran Pavunthan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/095', 
                'index_no'=>'S9468 ',
                'name'=>'Ranjith Rajakarunage Shashika Parakkarama Rajakaruna',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
            [
                'register_no'=>'2016/SP/098', 
                'index_no'=>'S9469 ',
                'name'=>'Ramadeniye Gedara Ravindu Dilshan Ramadeniye',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/102', 
                'index_no'=>'S9470 ',
                'name'=>'Lavanya Ratnabala',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/107', 
                'index_no'=>'S9471 ',
                'name'=>'Aththanayaka Pathiranage Pulinda Prabhath Sankalpa',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],		
               [
                'register_no'=>'2016/SP/115', 
                'index_no'=>'S9472 ',
                'name'=>'Raveendran Sirushdika',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/116', 
                'index_no'=>'S9473 ',
                'name'=>'Luxana Sivakumaran',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/156', 
                'index_no'=>'S9474 ',
                'name'=>'Thennakoon Pathirennehelage Geethmie Yasara Thennakoon',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
            [
                'register_no'=>'2016/SP/163', 
                'index_no'=>'S9475 ',
                'name'=>'Ilandarage Praveen Darshana Kularajapathi',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/164', 
                'index_no'=>'S9476 ',
                'name'=>'Konara Mudiyanselage Shakila Kalhari Gunathilake',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/167', 
                'index_no'=>'S9477 ',
                'name'=>'Meragalge Sarala Shalini Gunasekara',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],		
               [
                'register_no'=>'2016/SP/174', 
                'index_no'=>'S9478 ',
                'name'=>'Kaludurage Hashan Madusanka Rathnayaka',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/175', 
                'index_no'=>'S9479 ',
                'name'=>'Sivagnanasuntharam Sundaraathavan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/179', 
                'index_no'=>'S9480 ',
                'name'=>'Adhikari Athukoralalage Vinura Prabath Athukorala',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
            [
                'register_no'=>'2016/SP/183', 
                'index_no'=>'S9481 ',
                'name'=>'Mathangi Sivananthan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/193', 
                'index_no'=>'S9482 ',
                'name'=>'Senanayake Mudiyanselage Yasaransi Kaveesha Senanayake',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/200', 
                'index_no'=>'S9483 ',
                'name'=>'Kapuralalage Lasantha Chathuranga Bandara',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],		
               [
                'register_no'=>'2016/SP/204', 
                'index_no'=>'S9484 ',
                'name'=>'Paliskara Hemachandrage Isuru Lakruwan Ananda',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/208', 
                'index_no'=>'S9485 ',
                'name'=>'Lokuwithanage Yasiru Lakshan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/210', 
                'index_no'=>'S9486 ',
                'name'=>'Rammiah Jeyakumar',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/256', 
                'index_no'=>'S9487 ',
                'name'=>'Mohanras Anton Agnew Rathan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/259', 
                'index_no'=>'S9488 ',
                'name'=>'Mahadhevan Narththanan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/260', 
                'index_no'=>'S9489 ',
                'name'=>'Puvanendrarasa Rushanthan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/264', 
                'index_no'=>'S9490 ',
                'name'=>'Tharmika Kulenthiran',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/293', 
                'index_no'=>'S9491 ',
                'name'=>'Rathnasingam Sinthujan',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/298', 
                'index_no'=>'S9492 ',
                'name'=>'Konara Mudiyanselage Mahesh Bawantha Kulathunga',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/313', 
                'index_no'=>'S9493 ',
                'name'=>'Muharris Ahmadh Munzir',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/314', 
                'index_no'=>'S9494 ',
                'name'=>'Adikari Arachchige Chanaka Dushmantha Adikari',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/151', 
                'index_no'=>'S9495 ',
                'name'=>'Mohamed Musthafa Mohamed Zakee',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
           [
                'register_no'=>'2016/SP/311', 
                'index_no'=>'S9496 ',
                'name'=>'Mohamed Hamdoon Ijas Mohamed',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
            [
                'register_no'=>'2016/SP/221', 
                'index_no'=>'S9498 ',
                'name'=> 'Sulaimalebbe Rukzan Akeel',
                'level' =>'2G',
                'yos' =>'2016/2017',
               ],
   
           //3S
           [
                'register_no'=>'2015/CSC/002', 
                'index_no'=>'S9102 ',
                'name'=>'Mayuravaani Mathuranathan',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/006', 
                'index_no'=>'S9104 ',
                'name'=>'Mohamed Niwas Mohamed Muaz',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/012', 
                'index_no'=>'S9106 ',
                'name'=>'W.W.Chathuska Madhushan Waidyarathna',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/014', 
                'index_no'=>'S9107 ',
                'name'=>'Pravagaran Thamilvaanan',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/015', 
                'index_no'=>'S9108 ',
                'name'=>'N.W.G Anurudda Chathura Kumara Jeyawardane',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/016', 
                'index_no'=>'S9109 ',
                'name'=> 'Bhagya Udayangini Premarathne',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/017', 
                'index_no'=>'S9120 ',
                'name'=>'B.M Mahawalawwe Harsha Chaminda Bandra', 
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/019', 
                'index_no'=>'S9121 ',
                'name'=>'Herath Mudiyanselage Dhanuska Darmasena', 
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/021', 
                'index_no'=>'S9122 ',
                'name'=>'Walpola Kanakanamalage Athula Ranjan Walpola',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/023', 
                'index_no'=>'S9123 ',
                'name'=>'Wadiya Ralalage Isuri N Nadeeshanee Kalugalla',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/025', 
                'index_no'=>'S9124 ',
                'name'=>'Vihanga malinga Bandara Rasnakawewa',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/027', 
                'index_no'=>'S9130 ',
                'name'=>'Algewaththa Dolagarage Thaarindu Dilhara',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/028', 
                'index_no'=>'S9132 ',
                'name'=>'Anjalin Nirupa Nirmaleswaran',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/029', 
                'index_no'=>'S9134 ',
                'name'=>'Narmatha Jehanathan',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/030', 
                'index_no'=>'S9136 ',
                'name'=>'R. Mudianselage Pasan Lahiru Bandara Rathnayke',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/031', 
                'index_no'=>'S9138 ',
                'name'=>'Thayaparan Kalaineethan', 
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/032', 
                'index_no'=>'S9140 ',
                'name'=>'Justus Nithurshan',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/033', 
                'index_no'=>'S9141 ',
                'name'=>'Ranhotige Sujaanan Bhatiya Wijisinghe',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/034', 
                'index_no'=>'S9142 ',
                'name'=>'Thangavadivel Thanuskanth',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/035', 
                'index_no'=>'S9143 ',
                'name'=>'Theevika Arumaiththurai',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/036', 
                'index_no'=>'S9150 ',
                'name'=>'Mathalamuthu Vazz Dilanson',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/039', 
                'index_no'=>'S9155 ',
                'name'=>'J.Bandathuruge Kanchana Sandamali Pathirana',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/041', 
                'index_no'=>'S9156 ',
                'name'=>'Sivanesan Menuja',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/042', 
                'index_no'=>'S9157 ',
                'name'=>'W.M. Rayan Aradha',
                'level' =>'4M',
                'yos' =>'2014/2015',
               ],
           [
                'register_no'=>'2006/CSC/06', 
                'index_no'=>'S9158 ',
                'name'=>'Jesuthasu Samson', 
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/FS/40', 
                'index_no'=>'S9159 ',
                'name'=>'Ajaya Karki',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/CSC/038', 
                'index_no'=>'S970 ',
                'name'=>'Mathivannan Santhusan',
                'level' =>'3S',
                'yos' =>'2015/2016',
               ],
           
           
            //3G
            [
                'register_no'=>'2015/SP/405', 
                'index_no'=>'S9105 ',
                'name'=>'Gnanamoorthy Ananthan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/007', 
                'index_no'=>'S9110 ',
                'name'=>'Sithamaranathasharma Anusa',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/011', 
                'index_no'=>'S9111 ',
                'name'=>'Amalaseeli Arultharsan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/013', 
                'index_no'=>'S9112 ',
                'name'=>'Mohamed Akram Ashfaq Ahamed',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/018', 
                'index_no'=>'S8113 ',
                'name'=>'Wijerathna Rajakaruna Wasala Mudiyanselage Dilshika Dilshani',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/040', 
                'index_no'=>'S9114 ',
                'name'=>'Rathnayaka Mudiyanselage Suwendra Pradeep Gunawaedana',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/046', 
                'index_no'=>'S9115 ',
                'name'=>'Somapalage Dilan Madushankha Herath',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/054', 
                'index_no'=>'S8116 ',
                'name'=>'Samarakoon Mudiyanselage Malki Sandamini Jeyawardhana',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/065', 
                'index_no'=>'S9117 ',
                'name'=>'Thanidu Nawanjana Karunarathne',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/066', 
                'index_no'=>'S8118 ',
                'name'=>'Balasubramaniyam Kavidha',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/071', 
                'index_no'=>'S9119 ',
                'name'=>'Jeyasegedara Jayasundara Mudiyebselage Madhushanka Kumara',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/082', 
                'index_no'=>'S9125 ',
                'name'=>'Wimukthi Eroshan Mahawaduge',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/084', 
                'index_no'=>'S8127 ',
                'name'=>'Rajakaruna Mudiyanselage Ayodhya Hansamala Manewa',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/095', 
                'index_no'=>'S9128 ',
                'name'=>'Santhiranantham Nilogithan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/096', 
                'index_no'=>'S9129 ',
                'name'=>'Wickramasinghe Arachchige Dona Dilini Nimeshika',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/098', 
                'index_no'=>'S9131 ',
                'name'=>'Mahendran Niroshan', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/101', 
                'index_no'=>'S9133 ',
                'name'=>'Nirmalanathan Nivetha', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/121', 
                'index_no'=>'S9135 ',
                'name'=>'Kunathasan Rakavan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/127', 
                'index_no'=>'S9137 ',
                'name'=>'Peter Vimalathas Robinroy',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/128', 
                'index_no'=>'S9139 ',
                'name'=>'Bastian Koralalage Shevindi Navanjana Rodrigo',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2014/SP/135', 
                'index_no'=>'S9101 ',
                'name'=>'Sabgaranathan Sangarlal', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/139', 
                'index_no'=>'S8070 ',
                'name'=> 'Mahendran Saruhashini',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/141', 
                'index_no'=>'S9072 ',
                'name'=>'Matheews Sathurshan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/142', 
                'index_no'=>'S9073 ',
                'name'=>'Abirame Selvendran', 
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/144', 
                'index_no'=>'S9074 ',
                'name'=>'Rasamanickam Shahilashinie',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/146', 
                'index_no'=>'S9075 ',
                'name'=>'Nivethana Shanmugaratnam',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/148', 
                'index_no'=>'S9076 ',
                'name'=>'Karunanayake Shalintha Subhashana Silva', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/149', 
                'index_no'=>'S9077 ',
                'name'=>'Manikku Badathuruge Nuwani Uittara Karunawardhana Silva',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/153', 
                'index_no'=>'S9078 ',
                'name'=>'Samapavi Sriskandarajah', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/157', 
                'index_no'=>'S9079 ',
                'name'=>'Mathialagan Suhirthashini', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/167', 
                'index_no'=>'S8080 ',
                'name'=>'Lawshiga Thurairasasingam',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/168', 
                'index_no'=>'S9081 ',
                'name'=>'Jeyananthan Vithurshan', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/175', 
                'index_no'=>'S9082 ',
                'name'=>'Weerasingha Mudiyanselage Nadeeshani Kaushalya Weerasinga',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2012/SP/186', 
                'index_no'=>'S8083 ',
                'name'=>'Nirubikaa Ravakumar', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/189', 
                'index_no'=>'S9084 ',
                'name'=>'Gunasekara Widhanalage Nisal Shaminda Gunasekara',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2012/SP/194', 
                'index_no'=>'S9085 ',
                'name'=>'Meragal Pedige Dushyantha Thariju Priyankara',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/199', 
                'index_no'=>'S9086 ',
                'name'=>'Herath Mudiyanselage Ashan Harshana Bandara Herath',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/204', 
                'index_no'=>'S9087 ',
                'name'=> 'Viththiyanathan Pakeesan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/207', 
                'index_no'=>'S9088 ',
                'name'=>'Herath Mudiyanselage Sewmi Shayanara Herath',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/209', 
                'index_no'=>'S9089 ',
                'name'=>'Wedisingha Arachchilage Teneesha Jinanjanee Thilakarathna',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/211', 
                'index_no'=>'S9090 ',
                'name'=>'Jegatheesar Ruksala', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/213', 
                'index_no'=>'S9091 ',
                'name'=>'Ranasinghage Supun Dhanjaya Ranasingha',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/214', 
                'index_no'=>'S9092 ',
                'name'=>'Thaneawaran Thanujan',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/218', 
                'index_no'=>'S9093 ',
                'name'=>'Meerigama Dewage Gihan Priyankara Ranasingha',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/220', 
                'index_no'=>'S9094 ',
                'name'=>'Tharani Thanapalasingam',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/225', 
                'index_no'=>'S9095 ',
                'name'=>'Ethugal Pedige Rasanginee Sarangika Ethugala', 
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/248', 
                'index_no'=>'S9096 ',
                'name'=> 'Sivarajah Ainkaran',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/255', 
                'index_no'=>'S9097 ',
                'name'=>'Basthiyan Koralalage Marian Dilini Nuwanga Rodrigo',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/265', 
                'index_no'=>'S9098 ',
                'name'=>'Vijiththa Thangarajah',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/280', 
                'index_no'=>'S9099 ',
                'name'=>'W.Maralalage Akarshana Buddhini Chandrasena',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2013/SP/167', 
                'index_no'=>'S9100 ',
                'name'=>'Deepani Kaushalya Hemachandra',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2014/SP/170', 
                'index_no'=>'S9151 ',
                'name'=>'S.M.T.Madushani',
                'level' =>'3G',
                'yos' =>'2015/2016',
               ],
           
           //3M
          [
                'register_no'=>'2015/SP/505', 
                'index_no'=>'S8105 ',
                'name'=>'Gnanamoorthy Ananthan',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2014/SP/011', 
                'index_no'=>'S8111 ',
                'name'=>'Amalaseeli Arulthasan',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/018', 
                'index_no'=>'S9113 ',
                'name'=>'Wijerathna Rajakaruna Wasala Mudiyanselage Dilshika Dilshani',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/054', 
                'index_no'=>'S9116 ',
                'name'=>'Samarakoon Mudyanselage Malki Sandamini Jeyawardhana',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/066', 
                'index_no'=>'S9118 ',
                'name'=>'Balasubramaniyam Kavidha', 
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/084', 
                'index_no'=>'S9127 ',
                'name'=>'Rajakaruna Mudiyanselage Ayodhya Hansamala Manewa',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2015/SP/095', 
                'index_no'=>'S8128 ',
                'name'=>'Santhiranantham Nilogithan',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2014/SP/096', 
                'index_no'=>'S8129 ',
                'name'=>'Wikramasinghe Arachchige Dona Dilini Nimeshika',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/101', 
                'index_no'=>'S8133 ',
                'name'=>'Niormalanathan Nivetha',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2014/SP/127', 
                'index_no'=>'S8137 ',
                'name'=> 'Peter Vimalathas Robinroy',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
           [
                'register_no'=>'2014/SP/128', 
                'index_no'=>'S8139 ',
                'name'=>'Basthian Koralalage Shevindi Navanjana Rodrigo',
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
            [
                'register_no'=>'2015/SP/135', 
                'index_no'=>'S8101 ',
                'name'=> 'Sangaranathan Sangarlal', 
                'level' =>'3M',
                'yos' =>'2015/2016',
               ],
//            [
//                 'register_no'=>'2015/SP/139', 
//                 'index_no'=>'S9070 ',
//                 'name'=>'Mahendran Saruhashini', 
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//             [
//                 'register_no'=>'2014/SP/141', 
//                 'index_no'=>'S8072 ',
//                 'name'=>'Matheews Sathurshan', 
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//            [
//                 'register_no'=>'2014/SP/153', 
//                 'index_no'=>'S8078 ',
//                 'name'=>'Sampavi Sriskandarajah',
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//             [
//                 'register_no'=>'2014/SP/167', 
//                 'index_no'=>'S9080 ',
//                 'name'=>'Lawshiga Thurairasasingam',
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//            [
//                 'register_no'=>'2015/SP/186', 
//                 'index_no'=>'S9083 ',
//                 'name'=>'Nirubikaa Ravikumar', 
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//             [
//                 'register_no'=>'2015/SP/194', 
//                 'index_no'=>'S9085 ',
//                 'name'=>'Meragal pedige Dushyantha Thariju Priyankara',
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//            [
//                 'register_no'=>'2015/SP/207', 
//                 'index_no'=>'S9088 ',
//                 'name'=> 'Herath Mudiyanselage Sewmi Shayanara Herath', 
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//             [
//                 'register_no'=>'2015/SP/209', 
//                 'index_no'=>'S9089 ',
//                 'name'=>'Wedisingha Arachchilage Teneesha Jinanjanee Thilakarathna', 
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//            [
//                 'register_no'=>'2015/SP/225', 
//                 'index_no'=>'S9095 ',
//                 'name'=>'Ethugal Pedige pasanginee Sarangika Ethugala',
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//             [
//                 'register_no'=>'2015/SP/255', 
//                 'index_no'=>'S9097 ',
//                 'name'=>'Basthiyan Koralalage Marian Dilini Nuwanga Rodrigo', 
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//            [
//                 'register_no'=>'2015/SP/265', 
//                 'index_no'=>'S9098 ',
//                 'name'=>'Vijiththa Thangarajah',
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
//             [
//                 'register_no'=>'2015/SP/280', 
//                 'index_no'=>'S9099 ',
//                 'name'=>'W.Mralalage Akarshana Buddhini Chandrasena',
//                 'level' =>'3M',
//                 'yos' =>'2015/2016',
//                ],
   
//            //4S
//            [
//                 'register_no'=>'2014/CSC/003', 
//                 'index_no'=>'S9459 ',
//                 'name'=>'Sumandiran Jathurshan',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/010', 
//                 'index_no'=>'S9846 ',
//                 'name'=>'Mogan Kausik', 
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/012', 
//                 'index_no'=>'S9850 ',
//                 'name'=>'Nesathurai Pirunthapan',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/016', 
//                 'index_no'=>'S9851 ',
//                 'name'=>'Kumarasuinghe Bowalagamage Ranushka Pasindu Dharmaranga',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/017', 
//                 'index_no'=>'S9853 ',
//                 'name'=>'Jayalath Balagallage Sanjeewa Dias',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/018', 
//                 'index_no'=>'S9854 ',
//                 'name'=>'Amarasingam Thuvaragan',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/021', 
//                 'index_no'=>'S9856 ',
//                 'name'=>'Herath Mudiyanselage Chamara Madhusanka Bandara Rathnayaka',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/022', 
//                 'index_no'=>'S9857 ',
//                 'name'=>'Arebhy Sridaran', 
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/023', 
//                 'index_no'=>'S9859 ',
//                 'name'=> 'Yogeswaran Ligitha',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/024', 
//                 'index_no'=>'S9860 ',
//                 'name'=>'Balendran Saranya', 
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/025', 
//                 'index_no'=>'S9861 ',
//                 'name'=>'Rajan Prithweeraj',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/026', 
//                 'index_no'=>'S9862 ',
//                 'name'=>'Shanmugaratnam Kajaluxshan',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/027', 
//                 'index_no'=>'S9863 ',
//                 'name'=>'Tennakoon Mudiyanselage Saditha Udayanga Tennakoon', 
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/028', 
//                 'index_no'=>'S9864 ',
//                 'name'=>'Daundasekara Mudiyanselage Dhanushika Chamara Dissanayake',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/030', 
//                 'index_no'=>'S9865 ',
//                 'name'=>'Kuruwita Arachchillage Sahan Rajitha Thilakarathna',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/032', 
//                 'index_no'=>'S9866 ',
//                 'name'=>'Dhanapala Herath Mudiyanselage Dinusha Lakpriya',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/033', 
//                 'index_no'=>'S9867 ',
//                 'name'=>'Thennakoon Mudiyanselage Vikum Dheemantha Gunasekara',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/034', 
//                 'index_no'=>'S9868 ',
//                 'name'=>'Hetti Arachchilage cholaka Lahiru Madhushanka Senanayaka',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/035', 
//                 'index_no'=>'S9869 ',
//                 'name'=>'Selvarasa Paheerathan', 
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/036', 
//                 'index_no'=>'S9870 ',
//                 'name'=>'Arulananthasivam Tharshikan',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/037', 
//                 'index_no'=>'S9871 ',
//                 'name'=>'Kaleel Mohamed Hafni',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/038', 
//                 'index_no'=>'S9872 ',
//                 'name'=>'Nissanka Mudiyanaselage Sachini Iresha Nissanka',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/039', 
//                 'index_no'=>'S9873 ',
//                 'name'=>'Manathunga Mudiyanselage Ruchira Sachinthana Manathunga',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/040', 
//                 'index_no'=>'S9874 ',
//                 'name'=>'Hewa Suduhakuruge Ashan Sandaru Jayalath',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2013/CSC/018', 
//                 'index_no'=>'S9875 ',
//                 'name'=>'Muhammadu Haniffa Mohammadu Shifkhan',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//             [
//                 'register_no'=>'2014/CSC/FS/041', 
//                 'index_no'=>'S9876 ',
//                 'name'=>'Dhanesh Kumar',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/CSC/FS/042', 
//                 'index_no'=>'S9877 ',
//                 'name'=>'Md Sabbir Hossain',
//                 'level' =>'4S',
//                 'yos' =>'2014/2015',
//                ],
   
//            //4M
//            [
//                 'register_no'=>'2014/SP/015', 
//                 'index_no'=>'S9878 ',
//                 'name'=>'Mahalingam Antony Arulmalar',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/021', 
//                 'index_no'=>'S9879 ',
//                 'name'=>'Mohotti Gamage Anjula Keshan Priyanath',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/035', 
//                 'index_no'=>'S9880 ',
//                 'name'=>'Karunanithy Senthuja',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/042', 
//                 'index_no'=>'S9881 ',
//                 'name'=>'Meruja Selvamanikkam',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/057', 
//                 'index_no'=>'S9882 ',
//                 'name'=>'Pathamanathan Janani',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/058', 
//                 'index_no'=>'S9883 ',
//                 'name'=>'Suvendran Suganya',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/059', 
//                 'index_no'=>'S9884 ',
//                 'name'=>'Ratnasingam Kasthuriraajan', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/080', 
//                 'index_no'=>'S9885 ',
//                 'name'=>'Sivanathan Arunkumar', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/093', 
//                 'index_no'=>'S9886 ',
//                 'name'=>'Ganesharathinam Gopishanth', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/094', 
//                 'index_no'=>'S9887 ',
//                 'name'=>'Thramini Thalayasingam',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/103', 
//                 'index_no'=>'S9888 ',
//                 'name'=>'Kanapathipillai Kajasumanie',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/112', 
//                 'index_no'=>'S9889 ',
//                 'name'=>'Wasala Mudiyaneselage Dilani Madumini Gunawardhana',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/116', 
//                 'index_no'=>'S9890 ',
//                 'name'=>'T.M.Chathura Sampath Kumara Thennakoon',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/118', 
//                 'index_no'=>'S9891 ',
//                 'name'=>'Gammanpelahimi Arachchige Dushan Kshithija Tharaka', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/122', 
//                 'index_no'=>'S9892 ',
//                 'name'=> 'Arandarage Ramesh Madushanka', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/124', 
//                 'index_no'=>'S9893 ',
//                 'name'=>'Harischandra Patabendige Malki Maduka',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/125', 
//                 'index_no'=>'S9894 ',
//                 'name'=> 'Tharmakulasingam Thameera',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/127', 
//                 'index_no'=>'S9895 ',
//                 'name'=>'Archchitha Kanagarajah',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/130', 
//                 'index_no'=>'S9896 ',
//                 'name'=>'Sivarajah Mathura',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/131', 
//                 'index_no'=>'S9897 ',
//                 'name'=> 'Varnitha Sornalingam',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/137', 
//                 'index_no'=>'S9898 ',
//                 'name'=>'Thushani Raveendran', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/141', 
//                 'index_no'=>'S9899 ',
//                 'name'=>'Arangallage Lahiru Nirmal',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/142', 
//                 'index_no'=>'S9806 ',
//                 'name'=>'Kariyakarawanage Kasun Suminda Kariyakarawana Fernando',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/146', 
//                 'index_no'=>'S9788 ',
//                 'name'=>'Wickramasingha Senanayakage Hasitha Sandaruwan Senanayaka',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/149', 
//                 'index_no'=>'S9789 ',
//                 'name'=>'Angodage Shehan Akalanka Perera', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/158', 
//                 'index_no'=>'S9780 ',
//                 'name'=>'Ranathunga Mudiyanselage Shashikala Ranathunga',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/162', 
//                 'index_no'=>'S9781 ',
//                 'name'=>'Yogaratnam Shawmiya',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/163', 
//                 'index_no'=>'S9782 ',
//                 'name'=>'Kabilathas Parkavi',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/164', 
//                 'index_no'=>'S9783 ',
//                 'name'=>'Vithusha Mohan', 
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/165', 
//                 'index_no'=>'S9784 ',
//                 'name'=>'Kasturi Arachchige Tharuka Chathurani',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/179', 
//                 'index_no'=>'S9785 ',
//                 'name'=> 'Thewara Thanthirige Dushmanthi Madushani',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/186', 
//                 'index_no'=>'S9786 ',
//                 'name'=> 'Kanagaratnam Derushan',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ],
//            [
//                 'register_no'=>'2014/SP/202', 
//                 'index_no'=>'S9788 ',
//                 'name'=>'Kalu Arachchillage Kasun Mihiranga Kaluarachchi',
//                 'level' =>'4M',
//                 'yos' =>'2014/2015',
//                ]
//    ,
             
           
         ];
         foreach($students as $student){
             App\Student::create($student);
         }
    }
}
